"""about_me and last_seen included

Revision ID: 149cb8d8029b
Revises: 91094855c679
Create Date: 2018-09-08 20:20:31.266988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '149cb8d8029b'
down_revision = '91094855c679'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
